## Mikhail - Data
## Mikhail - VMatrix
PasSkills <- c("SoulAssault", "ShiningCross", "RoyalGuard", "AdvancedFinalAttack", "DeadlyCharge")
PasLvs <- c(50, 50, 50, 50, 50)
PasMP <- c(10, 10, 10, 10, 10)
ActSkills <- c("RhoAias", "ClaiomhSolais", "SwordofSoulLight", "LightofCourage", 
               "AuraWeapon", "CygnusPhalanx", "BodyofSteal", "BlessofCygnus", "SpiderInMirror")
ActLvs <- c(25, 25, 25, 25, 25, 25, 1, 25, 25)
ActMP <- c(5, 5, 5, 5, 5, 5, 0, 5, 0)
UsefulSkills <- c("CombatOrders", "SharpEyes")
UsefulLvs <- c(20, 20)
UsefulMP <- c(0, 0) ## SpiderInMirror DealRatio Check

CoreNumbers <- ceiling(sum(PasLvs) / 75) + length(ActSkills) + length(UsefulSkills)
if(CoreNumbers > Cores) {warning("Invalid Input")}

MPs <- ceiling(sum(PasMP) / 15) * 5 + sum(ActMP)
if(MPs > MatrixPoints) {warning("Invalid Input")}

PassiveCore <- data.frame(PasSkills, PasLvs + PasMP)
colnames(PassiveCore) <- c("Passive", "Levels")

ActiveCore <- data.frame(ActSkills, ActLvs + ActMP)
colnames(ActiveCore) <- c("Active", "Levels")

UsefulCore <- data.frame(UsefulSkills, UsefulLvs + UsefulMP)
colnames(UsefulCore) <- c("Useful", "Levels")
MikhailCore <- list(PassiveCore, ActiveCore, UsefulCore)


## Mikhail - Basic Info
MikhailClass1 <- ChrInfo[16, 2]
MikhailClass2 <- ChrInfo[16, 3]
MikhailMainStatType <- ChrInfo[16, 4]
MikhailSubStat1Type <- ChrInfo[16, 5]
MikhailChrLv <- ChrInfo[16, 7]
MikhailUnionLv <- ChrInfo[16, 8]
MikhailArcaneForce <- ChrInfo[16, 9]
MikhailCharisma <- ChrInfo[16, 10]
MikhailInsight <- ChrInfo[16, 11]
MikhailSensibility <- ChrInfo[16, 12]
MikhailBaseMastery <- ChrInfo[16, 13]
MikhailCRROver <- F
MikhailBuffDurationNeeded <- 0
RoyalGuardStack <- 5
RoyalGuardATK <- c(0, 10, 15, 20, 30, 45)
RoyalGuardDamage <- c(0, 275, 340, 440, 480, 565)
RoyalGuardATKCount <- c(0, 4, 5, 6, 7, 9)

MikhailAbility <- Abilities(c("BDR", "DisorderBDR"), c("L", "E"))

MikhailLinkBase <- rbind(LinkBase)
MikhailDisorder <- max(LinkBase$Disorder)
AdventureThief <- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ifelse(MikhailDisorder==T, (10+ServerLag)/20*18, 0), 0, 0, 0)
Cadena <- c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ifelse(MikhailDisorder==T, 6, 0)+ifelse(MikhailChrLv>MobLv, 6, 0), 0, 0, 0)
MikhailLinkBase <- rbind(LinkBase, DemonAvenger, Mikhail, Zero, CygnusKnights) ## Check Needed
MikhailLinkBase <- data.frame(MikhailLinkBase)
LinkSet <- c()
for(i in c(1:9, 11:13)) {
  LinkSet[i] <- sum(MikhailLinkBase[, i]) 
}
LinkSet[10] <- IGRCalc(MikhailLinkBase[, 10])
LinkSet <- data.frame(t(LinkSet))
colnames(LinkSet) <- colnames(MikhailLinkBase)[1:13]
rownames(LinkSet) <- c("Links")

CommonSkillSet <- data.frame(t(colSums(CommonSkills)))

MonsterLife <- colSums(MLTypeS22) ## IGR Logic Needed
MonsterLife <- data.frame(t(MonsterLife))

Dopings <- colSums(DopingSet) ## IGR Logic Needed
Dopings <- data.frame(t(Dopings))

Weapon <- rbind(WeaponUpgrade(1, 17, 4, 0, 0, 0, 0, 3, 0, 0, "Sword", "AR")[, 1:16], SubWeapon[18, ], Emblem[3, ])
rownames(Weapon) <- c("Weapon", "SubWeapon", "Emblem")
colnames(Weapon) <- SubWeaponOption
Weapon <- data.frame(Weapon)
Weapon <- WeaponAddpotential(Weapon, c("U", "U", "U"), c("A", "A", "O"))

Item <- rbind(SpecSet1, SetOption(SpecSet1, "AR"), PetSetOption(c("D", "D", "D")))
ItemSet <- c()
for(i in c(2:10, 17:19)) {
  ItemSet[i] <- sum(Item[, i])
}
ItemSet[16] <- IGRCalc(Item[, 16])
ItemSet <- data.frame(t(ItemSet))
colnames(ItemSet) <- colnames(Item)
rownames(ItemSet) <- c("Item")

Specs <- c("MainStat", "SubStat1", "ATK", "ATKP", "IGR", "BDR", "CRR", "CDMR", "FDR", "ATKSpeed", "Mastery", "BuffDuration", 
           "SummonedDuration", "ImmuneIgnore", "CoolTimeReset", "SkillLv", "PSkillLv", "CoolReduceP", "CoolReduce", "Disorder", "MainStatP")
MikhailSpec <- data.frame(t(rep(0, 21)))
colnames(MikhailSpec) <- Specs

MikhailSpec$SkillLv <- sum(MikhailCore[[3]][, 1]=="CombatOrders")
MikhailSpec$PSkillLv <- sum(MikhailCore[[3]][, 1]=="CombatOrders") + MikhailAbility$PassiveLv
MikhailSpec$MainStatP <- (100 + ItemSet$MainStatP + ItemSet$AllstatP + sum(Weapon$AllstatP) + Dopings$AllstatP + LinkSet$AllstatP) / 100 


## Mikhail - Passive
{option <- factor(c("ATKP"), levels=PSkill)
value <- c(10)
ElementalExpert <- data.frame(option, value)

option <- factor(c("ATK"), levels=PSkill)
value <- c(20)
Encourage <- data.frame(option, value)

option <- factor(c("FDR"), levels=PSkill)
value <- c(15)
SwordMastery <- data.frame(option, value)

option <- factor(c("MainStat", "SubStat1"), levels=PSkill)
value <- c(30, 30)
PhysicalTraining <- data.frame(option, value)

option <- factor(c("BDR"), levels=PSkill)
value <- c(5 * PartyMembers)
SoulLink <- data.frame(option, value)

option <- factor(c("ATK"), levels=PSkill)
value <- c(RoyalGuardATK[RoyalGuardStack+1])
AdvancedRoyalGuard <- data.frame(option, value)

option <- factor(c("MainStat", "CRR", "FDR", "ATKSpeed"), levels=PSkill)
value <- c(60, 20, 10, 1)
Intention <- data.frame(option, value)

option <- factor(c("FDR", "CRR"), levels=PSkill)
value <- c(25, 20)
SoulAttack <- data.frame(option, value)

option <- factor(c("BDR"), levels=PSkill)
value <- c(60)
ShiningCharge <- data.frame(option, value)

option <- factor(c("FDR", "CDMR"), levels=PSkill)
value <- c(30 + MikhailSpec$SkillLv, 8)
SoulRage <- data.frame(option, value)

option <- factor(c("Mastery", "ATK", "CRR", "CDMR"), levels=PSkill)
value <- c(70 + ceiling(MikhailSpec$SkillLv/2), 30 + MikhailSpec$SkillLv, 15 + floor(MikhailSpec$SkillLv/2), 10)
AdvnacedSwordMastery <- data.frame(option, value)

option <- factor(c("ATK"), levels=PSkill)
value <- c(30 + MikhailSpec$SkillLv)
AdvancedFinalAttack <- data.frame(option, value)

option <- factor(c("IGR"), levels=PSkill)
value <- c(40 + 2 * MikhailSpec$SkillLv)
CombatMastery <- data.frame(option, value)

option <- factor(c("MainStat"), levels=PSkill)
value <- c(MikhailCore[[2]][7, 2])
BodyofStealPassive <- data.frame(option, value)}

MikhailPassive <- Passive(list(ElementalExpert=ElementalExpert, Encourage=Encourage, SwordMastery=SwordMastery, PhysicalTraining=PhysicalTraining, 
                               SoulLink=SoulLink, AdvancedRoyalGuard=AdvancedRoyalGuard, Intention=Intention, SoulAttack=SoulAttack, ShiningCharge=ShiningCharge, 
                               SoulRage=SoulRage, AdvnacedSwordMastery=AdvnacedSwordMastery, AdvancedFinalAttack=AdvancedFinalAttack, CombatMastery=CombatMastery, BodyofStealPassive=BodyofStealPassive))


## Mikhail- Buff
{option <- factor("ATKSpeed", levels=BSkill)
value <- c(2)
info <- c(180, NA, 0, T, NA, NA, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
SwordBooster <- rbind(data.frame(option, value), info)

option <- factor("ATK", levels=BSkill)
value <- c(30)
info <- c(180, NA, 0, T, NA, NA, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
Encourage <- rbind(data.frame(option, value), info)

option <- factor("MainStat", levels=BSkill)
value <- c(floor((MikhailChrLv * 5 + 18) * (0.15 + 0.01 * ceiling(MikhailSpec$SkillLv/2))))
info <- c(900 + 30 * MikhailSpec$SkillLv, NA, 0, T, NA, NA, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
MapleSoldier <- rbind(data.frame(option, value), info)

option <- factor("BDR", levels=BSkill)
value <- c(20)
info <- c(30, 180, 900, T, T, T, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
MikhailLink <- rbind(data.frame(option, value), info)

option <- factor("BDR", levels=BSkill)
value <- c(10)
info <- c(10, 15, 0, F, F, F, F)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
DeadlyChargeBuff <- rbind(data.frame(option, value), info)

option <- factor("BDR", levels=BSkill)
value <- c(10)
info <- c(30, 210, 90, F, F, F, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
SacredCube <- rbind(data.frame(option, value), info)

option <- factor("BDR", levels=BSkill)
value <- c(5)
info <- c(120, 120, 0, F, F, F, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
QueenofTomorrow <- rbind(data.frame(option, value), info)

option <- factor("FDR", levels=BSkill)
value <- c(5 + floor(((10 + floor(MikhailCore[[2]][1, 2] / 4)) * 3 + 5)/2))
info <- c(75 + 3 * MikhailCore[[2]][1, 2], 300, 1680, F, T, F, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
RhoAias <- rbind(data.frame(option, value), info) ## FDR Buff Delay?

option <- factor(c("ATKP", "IGR", "CRR", "ATKSkill"), levels=BSkill)
value <- c(15 + floor(MikhailCore[[2]][3, 2]/2), 100, 100, 1)
info <- c(30, 180, 1050, F, T, F, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
SwordofSoulLight <- rbind(data.frame(option, value), info)

option <- factor(c("BDR", "ATKSkill"), levels=BSkill)
value <- c(10 + floor(MikhailCore[[2]][4, 2]/2), 1)
info <- c(25, 90, 990, F, T, F, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
LightofCourageBuff <- rbind(data.frame(option, value), info)

option <- factor(c("CRR", "CDMR"), levels=BSkill)
value <- c(10, 8)
info <- c(180 + 3 * MikhailCore[[3]][2, 2], NA, 900, F, NA, NA, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
UsefulSharpEyes <- rbind(data.frame(option, value), info)

option <- factor("SkillLv", levels=BSkill)
value <- c(1)
info <- c(180 + 3 * MikhailCore[[3]][1, 2], NA, 1500, F, NA, NA, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
UsefulCombatOrders <- rbind(data.frame(option, value), info)

option <- factor(c("IGR", "FDR", "ATKSkill"), levels=BSkill)
value <- c(10 + floor(MikhailCore[[2]][5, 2]/5), ceiling(MikhailCore[[2]][5, 2]/5), 1)
info <- c(80 + 2 * MikhailCore[[2]][5, 2], 180, 720, F, T, F, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
AuraWeaponBuff <- rbind(data.frame(option, value), info)

option <- factor(levels=BSkill)
value <- c()
info <- c(45, 240, 630, F, T, F, T)
info <- data.frame(BInfo, info)
colnames(info) <- c("option", "value")
BlessofCygnus <- rbind(data.frame(option, value), info)}

MikhailBuff <- Buff(list(SwordBooster=SwordBooster, Encourage=Encourage, MapleSoldier=MapleSoldier, MikhailLink=MikhailLink, DeadlyChargeBuff=DeadlyChargeBuff, SacredCube=SacredCube,
                         QueenofTomorrow=QueenofTomorrow, RhoAias=RhoAias, SwordofSoulLight=SwordofSoulLight, LightofCourageBuff=LightofCourageBuff, UsefulSharpEyes=UsefulSharpEyes, UsefulCombatOrders=UsefulCombatOrders,
                         AuraWeaponBuff=AuraWeaponBuff, BlessofCygnus=BlessofCygnus, Restraint4=Restraint4, SoulContractLink=SoulContractLink))
MikhailAllTimeBuff <- AllTimeBuff(MikhailBuff)
## PetBuff : SwordBooster, Encourage, MapleSolider


## Mikhail - Union & HyperStat & SoulWeapon
MikhailSpec$CRR <- sum(Weapon$CRR) + ItemSet$CRR + MonsterLife$CRR + Dopings$CRR + LinkSet$CRR + MikhailPassive$CRR + 
  (Union8000Chr$CRR) + MikhailAbility$CRR + MikhailAllTimeBuff$CRR + 5
MikhailSpec$CRR <- ifelse(MikhailCRROver==T, MikhailSpec$CRR, min(MikhailSpec$CRR, 100))
MikhailSpec$BuffDuration <- MonsterLife$BuffDuration + MikhailPassive$BuffDuration + Union8000Chr$BuffDuration + floor(MikhailSensibility/10) + MikhailAbility$BuffDuration

UnionFieldOption <- c("CDMR", "CRR", "BDR", "IGR", "BuffDuration", "MainStat", "SubStat1", "SubStat2", "ATK", "Stance")

UnionBase <- data.frame(t(c(40, 0, 0, 0, 0, 5, 1, 1, 5, 0)))
colnames(UnionBase) <- UnionFieldOption
UnionFields <- ifelse(MikhailUnionLv==8000, FieldNumbers[2], FieldNumbers[1]) - sum(UnionBase)

CRRs <- CRRGet(UnionFields, MikhailBuffDurationNeeded, MikhailSpec$BuffDuration, MikhailSpec$CRR, MikhailCRROver)
UnionBase <- UnionPlace(UnionFields - max(0, MikhailBuffDurationNeeded - MikhailSpec$BuffDuration) - CRRs$Union, UnionBase, 
                        max(0, MikhailBuffDurationNeeded - MikhailSpec$BuffDuration), CRRs$Union)
UnionBase$CDMR <- UnionBase$CDMR/2
UnionBase$MainStat <- UnionBase$MainStat*5
UnionBase$SubStat1 <- UnionBase$SubStat1*5
UnionBase$SubStat2 <- UnionBase$SubStat2*5
UnionRemained <- ifelse(MikhailUnionLv==8000, FieldNumbers[2], FieldNumbers[1]) - UnionBase$CDMR * 2 - UnionBase$CRR - UnionBase$BuffDuration - UnionBase$MainStat / 5 - UnionBase$SubStat1 / 5 - 
  UnionBase$SubStat2 / 5 - UnionBase$ATK - UnionBase$Stance

HyperStatBase <- data.frame(t(c(0, 0, 0, 10, 10, 10, ifelse(CRRs$Hyper<=5, CRRs$Hyper, 5+(CRRs$Hyper-5)/2), 10, 0)))
colnames(HyperStatBase) <- colnames(HyperStats)[2:10]
HyperSP <- 0
for(i in 1:9) {
  lvs <- HyperStatBase[1, i]
  HyperStatBase[1, i] <- ifelse(lvs==0, 0, sum(HyperStats[1:lvs, i+1]))
  HyperSP <- HyperSP + ifelse(lvs==0, 0, sum(HyperStats[1:lvs, 1]))
}

SoulWeaponOptions <- c("ATK", "ATKP", "CRR")
SoulWeapon <- data.frame(t(c(20, ifelse(CRRs[1, 3]==0, 3, 0), ifelse(CRRs[1, 3]==12, 12, 0))))
colnames(SoulWeapon) <- SoulWeaponOptions


## Mikhail Final Specs W/O UnionBDR&IGR, HyperStatAlpha, Potential
MikhailSpec$MainStat <- floor((sum(Weapon$MainStat) + ItemSet$MainStat + MonsterLife$STR + Dopings$MainStat + LinkSet$MainStat + MikhailPassive$MainStat + 
  MikhailAllTimeBuff$MainStat + CommonSkillSet$MainStat + UnionBase$MainStat + 18 + 5 * MikhailChrLv) * (100 + ItemSet$MainStatP + ItemSet$AllstatP + sum(Weapon$AllstatP) + 
  Dopings$AllstatP + LinkSet$AllstatP + MikhailPassive$MainStatP) / 100) + 10 * MikhailArcaneForce + Union8000Chr$STR
MikhailSpec$SubStat1 <- floor((sum(Weapon$SubStat1) + ItemSet$SubStat1 + MonsterLife$DEX + Dopings$SubStat1 + LinkSet$SubStat1 + MikhailPassive$SubStat1 + 
  MikhailAllTimeBuff$SubStat1 + CommonSkillSet$SubStat1 + UnionBase$SubStat1 + 4) * (100 + ItemSet$AllstatP + sum(Weapon$AllstatP) + Dopings$AllstatP + LinkSet$AllstatP) / 100) + 
  Union8000Chr$DEX
MikhailSpec$ATK <- sum(Weapon$ATK) + ItemSet$ATK + MonsterLife$ATK + Dopings$ATK + LinkSet$ATK + MikhailPassive$ATK + Union8000Chr$ATK + MikhailAbility$CRR + 
  MikhailAllTimeBuff$ATK + CommonSkillSet$ATK + UnionBase$ATK + SoulWeapon$ATK
MikhailSpec$ATKP <- sum(Weapon$ATKP) + MikhailPassive$ATKP + MikhailAllTimeBuff$ATKP + CommonSkillSet$ATKP + SoulWeapon$ATKP
MikhailSpec$IGR <- IGRCalc(c(IGRCalc(c(Weapon$IGR)), ItemSet$IGR, MonsterLife$IGR, Dopings$IGR, LinkSet$IGR, MikhailPassive$IGR, Union8000Chr$IGR, floor(MikhailCharisma/5)/2, 
  MikhailAllTimeBuff$IGR, HyperStatBase$IGR))
MikhailSpec$BDR <- sum(Weapon$BDR) + ItemSet$BDR + MonsterLife$BDR + Dopings$BDR + LinkSet$BDR + MikhailPassive$BDR + Union8000Chr$BDR + MikhailAbility$BDR + MikhailAbility$DisorderBDR + 
  MikhailAllTimeBuff$BDR + HyperStatBase$BDR + HyperStatBase$DMR
MikhailSpec$CRR <- sum(Weapon$CRR) + ItemSet$CRR + MonsterLife$CRR + Dopings$CRR + LinkSet$CRR + MikhailPassive$CRR + 
  (Union8000Chr$CRR + ifelse(MikhailChrLv>=250, 1, 0)) + MikhailAbility$CRR + MikhailAllTimeBuff$CRR + 5
MikhailSpec$CRR <- ifelse(MikhailCRROver==T, MikhailSpec$CRR + rowSums(CRRs), min(MikhailSpec$CRR + rowSums(CRRs), 100))
MikhailSpec$CDMR <- sum(Weapon$CDMR) + ItemSet$CDMR + MonsterLife$CDMR + Dopings$CDMR + LinkSet$CDMR + MikhailPassive$CDMR + MikhailAllTimeBuff$CDMR + Union8000Chr$CDMR +
  HyperStatBase$CDMR + UnionBase$CDMR
MikhailSpec$FDR <- FDRCalc(c(MikhailPassive$FDR, MikhailAllTimeBuff$FDR, ArcaneForceFDR(MikhailArcaneForce, MapArc), LevelFDR(MikhailChrLv, MobLv), 
  (WeaponUpgrade(1, 17, 4, 0, 0, 0, 0, 3, 0, 0, "Sword", "AR")[19]*100-100)))
MikhailSpec$ATKSpeed <- max(WeaponUpgrade(1, 17, 4, 0, 0, 0, 0, 3, 0, 0, "Sword", "AR")[17] - Dopings$ATKSpeed - MikhailAllTimeBuff$ATKSpeed - MikhailPassive$ATKSpeed, 2)
MikhailSpec$Mastery <- min(MikhailBaseMastery + MikhailPassive$Mastery, 95)
MikhailSpec$BuffDuration <- MikhailSpec$BuffDuration + UnionBase$BuffDuration
MikhailSpec$SummonedDuration <- MonsterLife$SummonedDuration + MikhailPassive$SummonDuration + Union8000Chr$SummonedDuration
MikhailSpec$ImmuneIgnore <- MikhailPassive$ImmuneIgnore + floor(MikhailInsight/10)/2 + MikhailAllTimeBuff$ImmuneIgnore
MikhailSpec$CoolTimeReset <- MonsterLife$CoolTimeReset + MikhailPassive$CoolTimeReset + MikhailAbility$CoolTimeReset
MikhailSpec$CoolReduceP <- Union8000Chr$CoolReduce
MikhailSpec$CoolReduce <- 0
MikhailSpec$Disorder <- max(MikhailLinkBase$Disorder, MikhailPassive$Disorder, MikhailAllTimeBuff$Disorder)


## Mikahil - Spider In Mirror
{option <- factor(levels=ASkill)
value <- c()
info <- c(450 + 18 * MikhailCore[[2]][9, 2], 15, 960, NA, 250, T, F, F)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
SpiderInMirror <- rbind(data.frame(option, value), info) 

option <- factor(levels=SSkill)
value <- c()
info <- c(0, 0, 0, 1800, 50, 250, F, T, F, F)
info <- data.frame(SInfo, info)
colnames(info) <- c("option", "value")
SpiderInMirrorStart <- rbind(data.frame(option, value), info)

option <- factor(levels=SSkill)
value <- c()
info <- c(175 + 7 * MikhailCore[[2]][9, 2], 8, 0, 0, 50, 250, F, T, F, F)
info <- data.frame(SInfo, info)
colnames(info) <- c("option", "value")
SpiderInMirror1 <- rbind(data.frame(option, value), info)

option <- factor(levels=SSkill)
value <- c()
info <- c(175 + 7 * MikhailCore[[2]][9, 2], 8, 0, 900, 50, 250, F, T, F, F)
info <- data.frame(SInfo, info)
colnames(info) <- c("option", "value")
SpiderInMirror2 <- rbind(data.frame(option, value), info)

option <- factor(levels=SSkill)
value <- c()
info <- c(175 + 7 * MikhailCore[[2]][9, 2], 8, 0, 850, 50, 250, F, T, F, F)
info <- data.frame(SInfo, info)
colnames(info) <- c("option", "value")
SpiderInMirror3 <- rbind(data.frame(option, value), info)

option <- factor(levels=SSkill)
value <- c()
info <- c(175 + 7 * MikhailCore[[2]][9, 2], 8, 0, 750, 50, 250, F, T, F, F)
info <- data.frame(SInfo, info)
colnames(info) <- c("option", "value")
SpiderInMirror4 <- rbind(data.frame(option, value), info)

option <- factor(levels=SSkill)
value <- c()
info <- c(175 + 7 * MikhailCore[[2]][9, 2], 8, 0, 650, 50, 250, F, T, F, F)
info <- data.frame(SInfo, info)
colnames(info) <- c("option", "value")
SpiderInMirror5 <- rbind(data.frame(option, value), info)

option <- factor(levels=SSkill)
value <- c()
info <- c(0, 0, 0, 5700, 50, 250, F, T, F, F)
info <- data.frame(SInfo, info)
colnames(info) <- c("option", "value")
SpiderInMirrorWait <- rbind(data.frame(option, value), info)}


## Mikhail - Attacks
{option <- factor(c("IGR", "BDR", "FDR"), levels=ASkill)
value <- c(ifelse(MikhailCore[[1]][1, 2]>=40, 20, 0), 20, 2 * MikhailCore[[1]][1, 2])
info <- c(210 + 3 * MikhailSpec$SkillLv, 12, 780, NA, NA, NA, NA, F)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
SoulAssault <- rbind(data.frame(option, value), info)

option <- factor(c("IGR", "BDR", "FDR"), levels=ASkill)
value <- c(ifelse(MikhailCore[[1]][2, 2]>=40, 20, 0), 20, 2 * MikhailCore[[1]][2, 2])
info <- c(440 + 3 * MikhailSpec$SkillLv, 5, 810, NA, NA, NA, NA, F)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
ShiningCross <- rbind(data.frame(option, value), info)

option <- factor(c("IGR", "FDR"), levels=ASkill)
value <- c(ifelse(MikhailCore[[1]][3, 2]>=40, 20, 0), 2 * MikhailCore[[1]][3, 2])
info <- c(RoyalGuardDamage[RoyalGuardStack+1] + MikhailChrLv, RoyalGuardATKCount[RoyalGuardStack+1], 600, NA, 6, T, T, T)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
RoyalGuard <- rbind(data.frame(option, value), info) ## No ATKSpeed

option <- factor(c("IGR", "FDR"), levels=ASkill)
value <- c(ifelse(MikhailCore[[1]][4, 2]>=40, 20, 0), 2 * MikhailCore[[1]][4, 2])
info <- c(95 + MikhailSpec$SkillLv, 4 * (0.75 + 0.01 * MikhailSpec$SkillLv), 0, NA, NA, NA, NA, F)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
AdvancedFinalAttack <- rbind(data.frame(option, value), info)

option <- factor(c("IGR", "FDR"), levels=ASkill)
value <- c(ifelse(MikhailCore[[1]][5, 2]>=40, 20, 0), 2 * MikhailCore[[1]][5, 2])
info <- c(600, 10, 1080, NA, 15, F, F, F)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
DeadlyCharge <- rbind(data.frame(option, value), info)

ClaiomhSolaisDamage <- c(350 + 14 * MikhailCore[[2]][2, 2], 350 + 14 * MikhailCore[[2]][2, 2], 420 + 16 * MikhailCore[[2]][2, 2],
                         510 + 20 * MikhailCore[[2]][2, 2], 600 + 24 * MikhailCore[[2]][2, 2], 700 + 28 * MikhailCore[[2]][2, 2])
option <- factor(levels=ASkill)
value <- c()
info <- c(ClaiomhSolaisDamage[RoyalGuardStack+1], 7, 0, NA, 12, T, F, F)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
ClaiomhSolais <- rbind(data.frame(option, value), info)

option <- factor(levels=ASkill)
value <- c()
info <- c(ClaiomhSolaisDamage[1], 7, 900, 5000, 12, T, F, F)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
ClaiomhSolaisAuto <- rbind(data.frame(option, value), info)

option <- factor(levels=ASkill)
value <- c()
info <- c(400 + 16 * MikhailCore[[2]][3, 2], 12, 810, NA, NA, NA, NA, F)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
SoulLightSlash <- rbind(data.frame(option, value), info)

option <- factor(levels=ASkill)
value <- c()
info <- c(325 + 13 * MikhailCore[[2]][4, 2], 5, 0, 2400, NA, NA, NA, F)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
LightofCourage <- rbind(data.frame(option, value), info)

option <- factor(levels=ASkill)
value <- c()
info <- c(175 + 7 * MikhailCore[[2]][4, 2], 2, 0, NA, NA, NA, NA, F)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
LightofCourageAddAttack <- rbind(data.frame(option, value), info)

option <- factor(levels=ASkill)
value <- c()
info <- c(375 + 15 * MikhailCore[[2]][4, 2], 10, 0, 132, NA, NA, NA, T)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
LightofCourageEnd <- rbind(data.frame(option, value), info) ## Hits Needed, SubTime : Average / StartDelay : 180

option <- factor(levels=ASkill)
value <- c()
info <- c(500 + 20 * HeroCore[[2]][5, 2], 6, 0, NA, NA, NA, NA, F)
info <- data.frame(AInfo, info)
colnames(info) <- c("option", "value")
AuraWeapon <- rbind(data.frame(option, value), info)}

MikhailATK <- Attack(list(SoulAssault=SoulAssault, ShiningCross=ShiningCross, RoyalGuard=RoyalGuard, AdvancedFinalAttack=AdvancedFinalAttack, DeadlyCharge=DeadlyCharge, 
                          ClaiomhSolais=ClaiomhSolais, ClaiomhSolaisAuto=ClaiomhSolaisAuto, SoulLightSlash=SoulLightSlash, LightofCourage=LightofCourage, LightofCourageAddAttack=LightofCourageAddAttack, 
                          LightofCourageEnd=LightofCourageEnd, AuraWeapon=AuraWeapon, SpiderInMirror=SpiderInMirror))


## Mikhail - Summoned
{option <- factor(c("IGR", "BDR", "FDR"), levels=SSkill)
value <- c(ifelse(MikhailCore[[1]][2, 2]>=40, 20, 0), 20, 2 * MikhailCore[[1]][2, 2])
info <- c(75, 5, 0, 810, 12, NA, F, NA, NA, F)
info <- data.frame(SInfo, info)
colnames(info) <- c("option", "value")
ShiningCrossInstall <- rbind(data.frame(option, value), info)

option <- factor(levels=SSkill)
value <- c()
info <- c(450 + 18 * MikhailCore[[2]][6, 2], 1, 780, 240, 0.24*89+0.25, 30, F, T, F, F)
info <- data.frame(SInfo, info)
colnames(info) <- c("option", "value")
CygnusPhalanx <- rbind(data.frame(option, value), info)}

MikhailSummoned <- Summoned(list(ShiningCrossInstall=ShiningCrossInstall, CygnusPhalanx=CygnusPhalanx, SpiderInMirrorStart=SpiderInMirrorStart, 
                                 SpiderInMirror1=SpiderInMirror1, SpiderInMirror2=SpiderInMirror2, SpiderInMirror3=SpiderInMirror3, 
                                 SpiderInMirror4=SpiderInMirror4, SpiderInMirror5=SpiderInMirror5, SpiderInMirrorWait=SpiderInMirrorWait))


## Mikhail - DealCycle & Deal Calculation
ATKFinal <- data.frame(MikhailATK)
ATKFinal$Delay[c(-3)] <- Delay(ATKFinal$Delay, MikhailSpec$ATKSpeed)[c(-3)]
ATKFinal$CoolTime <- Cooldown(ATKFinal$CoolTime, ATKFinal$CoolReduceAvailable, MikhailSpec$CoolReduceP, MikhailSpec$CoolReduce)

BuffFinal <- data.frame(MikhailBuff)
BuffFinal$CoolTime <- Cooldown(BuffFinal$CoolTime, BuffFinal$CoolReduceAvailable, MikhailSpec$CoolReduceP, MikhailSpec$CoolReduce)
BuffFinal$Duration <- BuffFinal$Duration + BuffFinal$Duration * ifelse(BuffFinal$BuffDurationAvailable==T, MikhailSpec$BuffDuration / 100, 0) +
  ifelse(BuffFinal$ServerLag==T, 3, 0)

SummonedFinal <- data.frame(MikhailSummoned)
SummonedFinal$CoolTime <- Cooldown(SummonedFinal$CoolTime, SummonedFinal$CoolReduceAvailable, MikhailSpec$CoolReduceP, MikhailSpec$CoolReduce)
SummonedFinal$Duration <- SummonedFinal$Duration + ifelse(SummonedFinal$SummonedDurationAvailable==T, SummonedFinal$Duration * MikhailSpec$SummonedDuration / 100, 0)

DealCycle <- c("Skills", "Time", rownames(MikhailBuff))
MikhailDealCycle <- t(rep(0, length(DealCycle)))
colnames(MikhailDealCycle) <- DealCycle

### 0 ~ 180s
{MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SwordBooster", "Encourage", "MapleSoldier", "UsefulSharpEyes", "UsefulCombatOrders", "QueenofTomorrow", 
                                               "AuraWeaponBuff", "RhoAias", "MikhailLink", "SacredCube", "BlessofCygnus"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SpiderInMirror", ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SwordofSoulLight"), BuffFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulLightSlash", 3)), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "LightofCourage", ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("LightofCourageBuff"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 4)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 5)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 3)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulLightSlash", 4)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SoulContractLink"), BuffFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "Restraint4", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 6)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulLightSlash", 4)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulLightSlash", "SoulLightSlash", "LightofCourageEnd", "SoulLightSlash", "SoulLightSlash"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge", "SoulAssault", "SoulAssault"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulAssault", 8)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 8)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge", rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "LightofCourage", ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("LightofCourageBuff"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 3)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SoulContractLink"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("QueenofTomorrow"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross", "LightofCourageEnd", "SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge", "SoulAssault", "SoulAssault", "SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)}

### 180 ~ 360s
{MikhailDealCycle <- DCBuff(MikhailDealCycle, c("AuraWeaponBuff", "MikhailLink"), BuffFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SwordofSoulLight"), BuffFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulLightSlash", 3)), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "LightofCourage", ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("LightofCourageBuff"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 4)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 5)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 3)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulLightSlash", 4)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SoulContractLink"), BuffFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "Restraint4", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 6)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulLightSlash", 4)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulLightSlash", "SoulLightSlash", "LightofCourageEnd", "SoulLightSlash", "SoulLightSlash"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge", "SoulAssault", "SoulAssault"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulAssault", 8)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 8)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SwordBooster", "Encourage", "UsefulSharpEyes", "UsefulCombatOrders", "QueenofTomorrow", "SacredCube", "BlessofCygnus"), BuffFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "LightofCourage", ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("LightofCourageBuff"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 3)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SoulContractLink"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("QueenofTomorrow"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross", "LightofCourageEnd", "SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge", "SoulAssault", "SoulAssault", "SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)}

### 360 ~ 540s
{MikhailDealCycle <- DCBuff(MikhailDealCycle, c("QueenofTomorrow", "AuraWeaponBuff", "RhoAias", "MikhailLink"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SpiderInMirror", ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SwordofSoulLight"), BuffFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulLightSlash", 3)), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "LightofCourage", ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("LightofCourageBuff"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 4)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 5)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 3)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulLightSlash", 4)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SoulContractLink"), BuffFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "Restraint4", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 6)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulLightSlash", 4)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulLightSlash", "SoulLightSlash", "LightofCourageEnd", "SoulLightSlash", "SoulLightSlash"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge", "SoulAssault", "SoulAssault"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulAssault", 8)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 8)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge", rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "LightofCourage", ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("LightofCourageBuff"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 3)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SoulContractLink"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SwordBooster", "Encourage", "UsefulSharpEyes", "UsefulCombatOrders", "SacredCube", "BlessofCygnus"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("QueenofTomorrow"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross", "LightofCourageEnd", "SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge", "SoulAssault", "SoulAssault", "SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)}

### 540 ~ 720s
{MikhailDealCycle <- DCBuff(MikhailDealCycle, c("AuraWeaponBuff", "MikhailLink"), BuffFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SwordofSoulLight"), BuffFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulLightSlash", 3)), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "LightofCourage", ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("LightofCourageBuff"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 4)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 5)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 3)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulLightSlash", 4)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SoulContractLink"), BuffFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "Restraint4", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulLightSlash", 6)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulLightSlash", 4)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "SoulLightSlash", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulLightSlash", "SoulLightSlash", "LightofCourageEnd", "SoulLightSlash", "SoulLightSlash"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge", "SoulAssault", "SoulAssault"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais", "ClaiomhSolaisAuto", rep("SoulAssault", 8)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 8)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "ShiningCross", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "LightofCourage", ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("LightofCourageBuff"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 3)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("SoulContractLink"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCBuff(MikhailDealCycle, c("QueenofTomorrow"), BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross", "LightofCourageEnd", "SoulAssault"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 5)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("DeadlyCharge", "SoulAssault", "SoulAssault", "SoulAssault"), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 4)), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "CygnusPhalanx", SummonedFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 6)), ATKFinal)
MikhailDealCycle <- DCBuff(MikhailDealCycle, "DeadlyChargeBuff", BuffFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, "DeadlyCharge", ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 9)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolais"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ClaiomhSolaisAuto"), ATKFinal)
MikhailDealCycle <- DCSummoned(MikhailDealCycle, "ShiningCrossInstall", SummonedFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c("ShiningCross"), ATKFinal)
MikhailDealCycle <- DCATK(MikhailDealCycle, c(rep("SoulAssault", 7)), ATKFinal)
MikhailDealCycle <- RoyalGuardCycle(MikhailDealCycle, ATKFinal, ATKFinal$CoolTime[3])}

MikhailDealCycle <- DealCycleFinal(MikhailDealCycle)
MikhailDealCycle <- MikhailBuffLogic(MikhailDealCycle)
MikhailDealCycle <- RepATKCycle(MikhailDealCycle, "ClaiomhSolaisAuto", 2, 5000, ATKFinal)
MikhailDealCycle <- RepATKCycle(MikhailDealCycle, "LightofCourage", 11, 2400, ATKFinal)
MikhailDealCycle <- RepATKCycle(MikhailDealCycle, "LightofCourageEnd", 6, 180, ATKFinal)
MikhailDealCycle <- DCSummonedATKs(MikhailDealCycle, Skill=c("ShiningCrossInstall", "CygnusPhalanx"), SummonedFinal)
MikhailDealCycle <- AuraWeaponCycleMikhail(MikhailDealCycle)
MikhailDealCycle <- AddATKCycleMikhail(MikhailDealCycle)
MikhailDealCycle <- DCSpiderInMirror(MikhailDealCycle, SummonedFinal)
MikhailDealCycle <- BlessofCygnusCycle(MikhailDealCycle, 6000, ServerLag, MikhailCore[[2]][8, 2])
MikhailDealCycleReduction <- DealCycleReduction(MikhailDealCycle, "BlessofCygnusBDR")

sum(na.omit(WindBreakerDealCalc(MikhailDealCycleReduction, ATKFinal, BuffFinal, SummonedFinal, MikhailSpec)))

MikhailSpecOpt1 <- WindBreakerOptimization1(MikhailDealCycleReduction, ATKFinal, BuffFinal, SummonedFinal, MikhailSpec, UnionRemained)
MikhailSpecOpt <- MikhailSpec
MikhailSpecOpt$ATKP <- MikhailSpecOpt$ATKP + MikhailSpecOpt1$ATKP
MikhailSpecOpt$BDR <- MikhailSpecOpt$BDR + MikhailSpecOpt1$BDR
MikhailSpecOpt$IGR <- IGRCalc(c(MikhailSpecOpt$IGR, MikhailSpecOpt1$IGR))

MikhailSpecOpt2 <- WindBreakerOptimization2(WindBreakerDealCycleReduction, ATKFinal, BuffFinal, SummonedFinal, MikhailSpecOpt, HyperStatBase, MikhailChrLv, MikhailCRROver)
MikhailFinalDPM <- WindBreakerDealCalc(MikhailDealCycle, ATKFinal, BuffFinal, SummonedFinal, MikhailSpecOpt2)
MikhailFinalDPMwithMax <- WindBreakerDealCalcWithMaxDMR(MikhailDealCycle, ATKFinal, BuffFinal, SummonedFinal, MikhailSpecOpt2)

DPMTver$Mikhail[1] <- sum(na.omit(MikhailFinalDPMwithMax)) / (696480 / 60000)
DPMTver$Mikhail[2] <- sum(na.omit(MikhailFinalDPM)) / (696480 / 60000) - sum(na.omit(MikhailFinalDPMwithMax)) / (696480 / 60000)

MikhailDealData <- data.frame(MikhailDealCycle$Skills, MikhailDealCycle$Time, MikhailDealCycle$Restraint4, MikhailFinalDPMwithMax, MikhailFinalDPM-MikhailFinalDPMwithMax)
colnames(MikhailDealData) <- c("Skills", "Time", "R4", "Deal", "Leakage")
subset(MikhailDealData, MikhailDealData$Leakage > 0)

MikhailRR <- MikhailDealData[230:383, ]
sum((MikhailRR$Deal)) ## 3,314,080,178,255

Mikhail40s <-  MikhailDealData[24:451, ]
sum((Mikhail40s$Deal)) ## 6,260,558,530,237

DealRatio(MikhailDealCycle, MikhailFinalDPMwithMax)